ALTER TABLE Users
Drop CONSTRAINT [PK__Users__3214EC072862E1D0]

ALTER TABLE Users
ADD CONSTRAINT PK_Person PRIMARY KEY (Id,Username);

ALTER TABLE Users
ADD CONSTRAINT LongerThenFive
CHECK (LEN(Password)>5)

ALTER TABLE Users
ADD DEFAULT GETDATE()
FOR LastLoginTime

ALTER TABLE Users
Drop CONSTRAINT [PK__Users__3214EC072862E1D0]

ALTER TABLE Users
ADD CONSTRAINT LongerThenThree
CHECK (LEN(Username)>3)

ALTER TABLE Users
ADD CONSTRAINT uq_Username
UNIQUE (Username)
